#!/usr/bin/env php
<?php

require __DIR__ . '/../vendor/autoload.php';

$commands  = include_once __DIR__ . '/../config/commands.php';
$command   = $argv[1] ?? 'list';

(new $commands[$command]())->run();